apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w2c3zyt5w-java-springboot
  janus-idp.io/tekton: w2c3zyt5w-java-springboot
  backstage.io/kubernetes-id: w2c3zyt5w-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w2c3zyt5w-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
